#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# DON'T TOUCH THIS FILE IF YOU DON'T KNOW WHAT YOU ARE DOING

# Check if the last commit was in extensions/chrome_v1
if git log -1 --name-only --pretty=format: | grep "^extensions/chrome_v1" > /dev/null; then
  echo "Changes detected in chrome_v1, running git fetch..."
  git fetch
fi

# TODO: config this for other extensions too
